"""Add user_name field to users table

Revision ID: 3b289bf0bae0
Revises: 8344253a5ceb
Create Date: 2026-02-27 20:02:44.842507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b289bf0bae0'
down_revision = '8344253a5ceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
