"""Add message field to users table

Revision ID: 8344253a5ceb
Revises: a7a91fdf27af
Create Date: 2026-02-27 19:48:51.697704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8344253a5ceb'
down_revision = 'a7a91fdf27af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'message')
    # ### end Alembic commands ###
