"""Add message table

Revision ID: 8aff6aea8e5c
Revises: 3b289bf0bae0
Create Date: 2026-03-01 12:26:16.308298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aff6aea8e5c'
down_revision = '3b289bf0bae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
