"""Add message table

Revision ID: 910d0826818d
Revises: 8aff6aea8e5c
Create Date: 2026-03-01 21:27:55.997680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910d0826818d'
down_revision = '8aff6aea8e5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
